[package]
name = "rs-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.27.3"
config = "0.14.0"
dotenv = "0.15"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
tokio = "1.40.0"
serde_json = "1.0.128"

